# Generated by Django 5.1.6 on 2025-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_customuser_user_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=100),
        ),
    ]
