# Generated by Django 5.1.6 on 2025-03-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
