# Generated by Django 5.1.6 on 2025-03-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_stripe_price_id'),
        ('api', '0011_message_room'),
    ]

    operations = [
    ]
