# Generated by Django 5.1.6 on 2025-03-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_booking_rename_payment_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
